"""create document, job, and analysis tables

Revision ID: c2f7c2170983
Revises: 
Create Date: 2026-07-28 08:56:58.968174+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c2f7c2170983'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('byte_size >= 0', name='ck_documents_byte_size_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_content_sha256'), 'documents', ['content_sha256'], unique=False)
    op.create_table('ai_detection_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=True),
    sa.Column('document_title', sa.String(length=255), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ai_probability', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('perplexity', sa.Float(), nullable=False),
    sa.Column('burstiness', sa.Float(), nullable=False),
    sa.Column('signals', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('sentences', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('suspected_models', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('ai_probability >= 0 and ai_probability <= 1', name='ck_ai_detection_probability_unit'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_detection_results_analyzed_at', 'ai_detection_results', ['analyzed_at'], unique=False)
    op.create_table('document_payloads',
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('parse_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('failure', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.CheckConstraint("stage in ('queued', 'detecting_format', 'extracting_text', 'sanitizing', 'structuring', 'done')", name='ck_parse_jobs_stage'),
    sa.CheckConstraint("status in ('queued', 'running', 'completed', 'failed')", name='ck_parse_jobs_status'),
    sa.CheckConstraint('progress >= 0 and progress <= 1', name='ck_parse_jobs_progress_unit'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_parse_jobs_status_updated_at', 'parse_jobs', ['status', 'updated_at'], unique=False)
    op.create_table('plagiarism_checks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=True),
    sa.Column('document_title', sa.String(length=255), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('overall_similarity', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('overall_similarity >= 0 and overall_similarity <= 1', name='ck_plagiarism_checks_similarity_unit'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_plagiarism_checks_checked_at', 'plagiarism_checks', ['checked_at'], unique=False)
    op.create_table('parse_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('document_format', sa.String(length=16), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('sections', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('chunks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('truncated', sa.Integer(), nullable=False),
    sa.Column('warnings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.CheckConstraint('word_count >= 0', name='ck_parse_results_word_count_non_negative'),
    sa.ForeignKeyConstraint(['job_id'], ['parse_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parse_results')
    op.drop_index('ix_plagiarism_checks_checked_at', table_name='plagiarism_checks')
    op.drop_table('plagiarism_checks')
    op.drop_index('ix_parse_jobs_status_updated_at', table_name='parse_jobs')
    op.drop_table('parse_jobs')
    op.drop_table('document_payloads')
    op.drop_index('ix_ai_detection_results_analyzed_at', table_name='ai_detection_results')
    op.drop_table('ai_detection_results')
    op.drop_index(op.f('ix_documents_content_sha256'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
